import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, UserRound } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { useTenant } from "@/lib/tenant-context";

type RefRow={id:string;name:string;status:string;department_id?:string|null;position_id?:string|null};
type Employee={id:string;name:string;status:string;department_id:string|null;position_id:string|null;function_id:string|null;admission_date:string|null;termination_date:string|null};
type Form={id:string|null;name:string;status:string;department_id:string;position_id:string;function_id:string;admission_date:string;termination_date:string;cpf:string;rg:string;birth_date:string;sex:string;marital_status:string;nationality:string;birth_place:string;mother_name:string;father_name:string;phone:string;email:string;emergency_contact_name:string;emergency_contact_relationship:string;emergency_contact_phone:string;postal_code:string;street:string;number:string;complement:string;district:string;city:string;state:string;pis_pasep:string;ctps:string;voter_registration:string;military_certificate:string;cnh:string;cnh_category:string;cnh_expires_at:string;bank_name:string;agency:string;account_number:string;account_type:string;pix_key:string;salary:string};
const empty:Form={id:null,name:"",status:"ativo",department_id:"",position_id:"",function_id:"",admission_date:"",termination_date:"",cpf:"",rg:"",birth_date:"",sex:"",marital_status:"",nationality:"Brasileira",birth_place:"",mother_name:"",father_name:"",phone:"",email:"",emergency_contact_name:"",emergency_contact_relationship:"",emergency_contact_phone:"",postal_code:"",street:"",number:"",complement:"",district:"",city:"",state:"",pis_pasep:"",ctps:"",voter_registration:"",military_certificate:"",cnh:"",cnh_category:"",cnh_expires_at:"",bank_name:"",agency:"",account_number:"",account_type:"",pix_key:"",salary:""};
const input="h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring";
const sections=["Profissional","Pessoal","Endereço","Documentos","Banco e remuneração"] as const;
function val(v:string){return v.trim()||null} function digits(v:string){return v.replace(/\D/g,"")}
export function EmployeeManager({departments,positions,functions}:{departments:RefRow[];positions:RefRow[];functions:RefRow[]}){
 const supabase=getSupabase(); const {tenant}=useTenant(); const tenantId=tenant?.id??null;
 const [rows,setRows]=useState<Employee[]>([]),[form,setForm]=useState<Form>(empty),[editing,setEditing]=useState(false),[section,setSection]=useState<(typeof sections)[number]>("Profissional"),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[ok,setOk]=useState<string|null>(null);
 const positionsFiltered=useMemo(()=>positions.filter(x=>x.status==="ativo"&&(!form.department_id||!x.department_id||x.department_id===form.department_id)),[positions,form.department_id]);
 const functionsFiltered=useMemo(()=>functions.filter(x=>x.status==="ativo"&&(!form.department_id||!x.department_id||x.department_id===form.department_id)&&(!form.position_id||!x.position_id||x.position_id===form.position_id)),[functions,form.department_id,form.position_id]);
 async function load(){if(!supabase||!tenantId)return;const {data,error}=await supabase.from("rh_employees").select("id,name,status,department_id,position_id,function_id,admission_date,termination_date").eq("tenant_id",tenantId).is("deleted_at",null).order("name");if(error)setError(error.message);else setRows((data??[]) as Employee[])}
 useEffect(()=>{void load()},[tenantId]);
 function start(){setForm(empty);setSection("Profissional");setEditing(true);setError(null);setOk(null)}
 async function edit(e:Employee){if(!supabase||!tenantId)return;setError(null);const [p,a,d,b,c]=await Promise.all([supabase.from("rh_employee_personal_details").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_addresses").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_documents").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_bank_accounts").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_compensation").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle()]);const bad=[p,a,d,b,c].find(x=>x.error);if(bad?.error){setError(bad.error.message);return}const x:any={...empty,...e,...(p.data||{}),...(a.data||{}),...(d.data||{}),...(b.data||{}),...(c.data||{}),id:e.id,salary:c.data?.salary==null?"":String(c.data.salary)};for(const k of Object.keys(empty) as (keyof Form)[])if(x[k]===null)x[k]="";setForm(x);setSection("Profissional");setEditing(true)}
 async function upsert(table:string,employeeId:string,payload:Record<string,unknown>){if(!supabase||!tenantId)return;const {data}=await supabase.from(table).select("id").eq("tenant_id",tenantId).eq("employee_id",employeeId).maybeSingle();const q=data?.id?supabase.from(table).update(payload).eq("id",data.id):supabase.from(table).insert({tenant_id:tenantId,employee_id:employeeId,...payload});const {error}=await q;if(error)throw error}
 async function save(){if(!supabase||!tenantId||!form.name.trim())return;setSaving(true);setError(null);setOk(null);try{const {data:u,error:ue}=await supabase.auth.getUser();if(ue)throw ue;const main={tenant_id:tenantId,name:form.name.trim(),status:form.status,department_id:val(form.department_id),position_id:val(form.position_id),function_id:val(form.function_id),admission_date:val(form.admission_date),termination_date:val(form.termination_date),updated_by:u.user?.id??null};let employeeId=form.id;if(employeeId){const {error}=await supabase.from("rh_employees").update(main).eq("id",employeeId).eq("tenant_id",tenantId);if(error)throw error}else{const {data,error}=await supabase.from("rh_employees").insert({...main,created_by:u.user?.id??null}).select("id").single();if(error)throw error;employeeId=data.id}
 const personal={cpf:val(form.cpf)?digits(form.cpf):null,rg:val(form.rg),birth_date:val(form.birth_date),sex:val(form.sex),marital_status:val(form.marital_status),nationality:val(form.nationality),birth_place:val(form.birth_place),mother_name:val(form.mother_name),father_name:val(form.father_name),phone:val(form.phone),email:val(form.email),emergency_contact_name:val(form.emergency_contact_name),emergency_contact_relationship:val(form.emergency_contact_relationship),emergency_contact_phone:val(form.emergency_contact_phone)};
 await upsert("rh_employee_personal_details",employeeId!,personal);await upsert("rh_employee_addresses",employeeId!,{postal_code:val(form.postal_code),street:val(form.street),number:val(form.number),complement:val(form.complement),district:val(form.district),city:val(form.city),state:val(form.state)});await upsert("rh_employee_documents",employeeId!,{pis_pasep:val(form.pis_pasep),ctps:val(form.ctps),voter_registration:val(form.voter_registration),military_certificate:val(form.military_certificate),cnh:val(form.cnh),cnh_category:val(form.cnh_category),cnh_expires_at:val(form.cnh_expires_at)});await upsert("rh_employee_bank_accounts",employeeId!,{bank_name:val(form.bank_name),agency:val(form.agency),account_number:val(form.account_number),account_type:val(form.account_type),pix_key:val(form.pix_key)});await upsert("rh_employee_compensation",employeeId!,{salary:form.salary.trim()===""?null:Number(form.salary.replace(",","."))});setEditing(false);setForm(empty);setOk("Colaborador salvo com sucesso.");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o colaborador.")}finally{setSaving(false)}}
 const F=({k,label,type="text"}:{k:keyof Form;label:string;type?:string})=><label className="space-y-1.5"><span className="text-sm font-medium">{label}</span><input type={type} className={input} value={String(form[k]??"")} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>;
 return <div className="space-y-4">{error&&<div className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}{ok&&<div className="rounded-md border border-emerald-500/40 bg-emerald-500/10 p-3 text-sm">{ok}</div>}
 {!editing&&<><div className="flex justify-end"><button onClick={start} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><Plus className="h-4 w-4"/>Novo colaborador</button></div>{rows.length===0?<div className="rounded-lg border border-dashed p-8 text-center"><UserRound className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><div className="font-semibold">Nenhum colaborador cadastrado</div></div>:<div className="grid gap-3 md:grid-cols-2">{rows.map(r=><div key={r.id} className="rounded-lg border p-4 flex justify-between gap-3"><div><div className="font-semibold">{r.name}</div><div className="text-sm text-muted-foreground">{r.status}</div></div><button onClick={()=>void edit(r)} className="rounded-md p-2 hover:bg-muted"><Pencil className="h-4 w-4"/></button></div>)}</div>}</>}
 {editing&&<div className="space-y-5"><div className="flex flex-wrap gap-2">{sections.map(s=><button key={s} onClick={()=>setSection(s)} className={`rounded-md border px-3 py-2 text-sm ${section===s?"bg-primary text-primary-foreground":"bg-background"}`}>{s}</button>)}</div><div className="grid gap-4 md:grid-cols-2">
 {section==="Profissional"&&<><F k="name" label="Nome completo *"/><label className="space-y-1.5"><span className="text-sm font-medium">Status</span><select className={input} value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}><option value="ativo">Ativo</option><option value="inativo">Inativo</option><option value="desligado">Desligado</option></select></label><label className="space-y-1.5"><span className="text-sm font-medium">Departamento</span><select className={input} value={form.department_id} onChange={e=>setForm(v=>({...v,department_id:e.target.value,position_id:"",function_id:""}))}><option value="">Selecione</option>{departments.filter(x=>x.status==="ativo").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="space-y-1.5"><span className="text-sm font-medium">Cargo</span><select className={input} value={form.position_id} onChange={e=>setForm(v=>({...v,position_id:e.target.value,function_id:""}))}><option value="">Selecione</option>{positionsFiltered.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="space-y-1.5"><span className="text-sm font-medium">Função</span><select className={input} value={form.function_id} onChange={e=>setForm(v=>({...v,function_id:e.target.value}))}><option value="">Selecione</option>{functionsFiltered.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><F k="admission_date" label="Admissão" type="date"/><F k="termination_date" label="Desligamento" type="date"/></>}
 {section==="Pessoal"&&<><F k="cpf" label="CPF"/><F k="rg" label="RG"/><F k="birth_date" label="Nascimento" type="date"/><F k="sex" label="Sexo"/><F k="marital_status" label="Estado civil"/><F k="nationality" label="Nacionalidade"/><F k="birth_place" label="Naturalidade"/><F k="phone" label="Telefone"/><F k="email" label="E-mail" type="email"/><F k="mother_name" label="Nome da mãe"/><F k="father_name" label="Nome do pai"/><F k="emergency_contact_name" label="Contato de emergência"/><F k="emergency_contact_relationship" label="Parentesco"/><F k="emergency_contact_phone" label="Telefone de emergência"/></>}
 {section==="Endereço"&&<><F k="postal_code" label="CEP"/><F k="street" label="Logradouro"/><F k="number" label="Número"/><F k="complement" label="Complemento"/><F k="district" label="Bairro"/><F k="city" label="Cidade"/><F k="state" label="UF"/></>}
 {section==="Documentos"&&<><F k="pis_pasep" label="PIS/PASEP"/><F k="ctps" label="CTPS"/><F k="voter_registration" label="Título de eleitor"/><F k="military_certificate" label="Reservista"/><F k="cnh" label="CNH"/><F k="cnh_category" label="Categoria CNH"/><F k="cnh_expires_at" label="Validade CNH" type="date"/></>}
 {section==="Banco e remuneração"&&<><F k="bank_name" label="Banco"/><F k="agency" label="Agência"/><F k="account_number" label="Conta"/><F k="account_type" label="Tipo de conta"/><F k="pix_key" label="Chave PIX"/><F k="salary" label="Salário" type="number"/></>}
 </div><div className="flex justify-end gap-2"><button className="h-10 rounded-md border px-4 text-sm" onClick={()=>setEditing(false)}>Cancelar</button><button disabled={saving||!form.name.trim()} className="h-10 rounded-md bg-primary px-5 text-sm font-medium text-primary-foreground disabled:opacity-50" onClick={()=>void save()}>{saving?"Salvando...":"Salvar colaborador"}</button></div></div>}
 </div>
}
