import { useEffect, useMemo, useRef, useState } from "react";
import { Pencil, Plus, UserRound } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { useTenant } from "@/lib/tenant-context";

type RefRow={id:string;name:string;status:string;department_id?:string|null;position_id?:string|null};
type Employee={id:string;name:string;status:string;department_id:string|null;position_id:string|null;function_id:string|null;admission_date:string|null;termination_date:string|null};
type Form={id:string|null;name:string;status:string;department_id:string;position_id:string;function_id:string;admission_date:string;termination_date:string;cpf:string;rg:string;birth_date:string;sex:string;marital_status:string;nationality:string;birth_place:string;mother_name:string;father_name:string;phone:string;email:string;emergency_contact_name:string;emergency_contact_relationship:string;emergency_contact_phone:string;postal_code:string;street:string;number:string;complement:string;district:string;city:string;state:string;pis_pasep:string;ctps:string;voter_registration:string;military_certificate:string;cnh:string;cnh_category:string;cnh_expires_at:string;bank_name:string;agency:string;account_number:string;account_type:string;pix_key:string;salary:string};
type Uf={id:number;sigla:string;nome:string}; type City={id:number;nome:string}; type Bank={ispb:string;name:string;code:number|null;fullName:string};
type PixType=""|"cpf"|"email"|"phone"|"random"|"other";
const empty:Form={id:null,name:"",status:"ativo",department_id:"",position_id:"",function_id:"",admission_date:"",termination_date:"",cpf:"",rg:"",birth_date:"",sex:"",marital_status:"",nationality:"Brasileira",birth_place:"",mother_name:"",father_name:"",phone:"",email:"",emergency_contact_name:"",emergency_contact_relationship:"",emergency_contact_phone:"",postal_code:"",street:"",number:"",complement:"",district:"",city:"",state:"",pis_pasep:"",ctps:"",voter_registration:"",military_certificate:"",cnh:"",cnh_category:"",cnh_expires_at:"",bank_name:"",agency:"",account_number:"",account_type:"",pix_key:"",salary:""};
const input="h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring";
const sections=["Profissional","Pessoal","Endereço","Documentos","Banco e remuneração"] as const;
const sexes=["Masculino","Feminino","Não informar"]; const marital=["Solteiro(a)","Casado(a)","União estável","Separado(a)","Divorciado(a)","Viúvo(a)"]; const accountTypes=["Conta corrente","Conta poupança","Conta salário","Conta de pagamento"]; const cnhCategories=["A","B","AB","C","AC","D","AD","E","AE"];
function val(v:string){return v.trim()||null} function digits(v:string){return v.replace(/\D/g,"")}
function maskCpf(v:string){const d=digits(v).slice(0,11);return d.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/,"$1-$2")}
function maskCep(v:string){const d=digits(v).slice(0,8);return d.replace(/(\d{5})(\d)/,"$1-$2")}
function maskPhone(v:string){let d=digits(v);const has55=/^\s*\+?55(?:\D|$)/.test(v)||v.trim().startsWith("+55");if(has55&&d.startsWith("55"))d=d.slice(2);d=d.slice(0,11);if(!d)return "";if(d.length<=2)return `+55 (${d}`;const ddd=d.slice(0,2),n=d.slice(2);if(!n)return `+55 (${ddd}) `;if(n.length<=4)return `+55 (${ddd}) ${n}`;if(n.length<=8)return `+55 (${ddd}) ${n.slice(0,4)}-${n.slice(4)}`;return `+55 (${ddd}) ${n.slice(0,5)}-${n.slice(5)}`}
function Field({form,setForm,k,label,type="text",mask}:{form:Form;setForm:React.Dispatch<React.SetStateAction<Form>>;k:keyof Form;label:string;type?:string;mask?:(v:string)=>string}){return <label className="space-y-1.5"><span className="text-sm font-medium">{label}</span><input type={type} className={input} value={String(form[k]??"")} onChange={e=>setForm(v=>({...v,[k]:mask?mask(e.target.value):e.target.value}))}/></label>}
function Select({label,value,onChange,children,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode;disabled?:boolean}){return <label className="space-y-1.5"><span className="text-sm font-medium">{label}</span><select disabled={disabled} className={input} value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
export function EmployeeManagerEnhanced({departments,positions,functions}:{departments:RefRow[];positions:RefRow[];functions:RefRow[]}){
 const supabase=getSupabase(); const {tenant}=useTenant(); const tenantId=tenant?.id??null;
 const [rows,setRows]=useState<Employee[]>([]),[form,setForm]=useState<Form>(empty),[editing,setEditing]=useState(false),[section,setSection]=useState<(typeof sections)[number]>("Profissional"),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[ok,setOk]=useState<string|null>(null);
 const [ufs,setUfs]=useState<Uf[]>([]),[birthUf,setBirthUf]=useState(""),[birthCities,setBirthCities]=useState<City[]>([]),[addressCities,setAddressCities]=useState<City[]>([]),[banks,setBanks]=useState<Bank[]>([]),[pixType,setPixType]=useState<PixType>("");
 const formRef=useRef(form);formRef.current=form;
 useEffect(()=>{void fetch("https://servicodados.ibge.gov.br/api/v1/localidades/estados?orderBy=nome").then(r=>r.json()).then(setUfs).catch(()=>setUfs([]));void fetch("https://brasilapi.com.br/api/banks/v1").then(r=>r.json()).then((x:Bank[])=>setBanks(x.filter(b=>b.name).sort((a,b)=>{if(a.code==null&&b.code==null)return a.name.localeCompare(b.name);if(a.code==null)return 1;if(b.code==null)return -1;return a.code-b.code||a.name.localeCompare(b.name)}))).catch(()=>setBanks([]))},[]);
 useEffect(()=>{if(!birthUf){setBirthCities([]);return}void fetch(`https://servicodados.ibge.gov.br/api/v1/localidades/estados/${birthUf}/municipios?orderBy=nome`).then(r=>r.json()).then(setBirthCities).catch(()=>setBirthCities([]))},[birthUf]);
 useEffect(()=>{if(!form.state){setAddressCities([]);return}void fetch(`https://servicodados.ibge.gov.br/api/v1/localidades/estados/${form.state}/municipios?orderBy=nome`).then(r=>r.json()).then(setAddressCities).catch(()=>setAddressCities([]))},[form.state]);
 const positionsFiltered=useMemo(()=>positions.filter(x=>x.status==="ativo"&&(!form.department_id||!x.department_id||x.department_id===form.department_id)),[positions,form.department_id]);
 const functionsFiltered=useMemo(()=>functions.filter(x=>x.status==="ativo"&&(!form.department_id||!x.department_id||x.department_id===form.department_id)&&(!form.position_id||!x.position_id||x.position_id===form.position_id)),[functions,form.department_id,form.position_id]);
 async function load(){if(!supabase||!tenantId)return;const {data,error}=await supabase.from("rh_employees").select("id,name,status,department_id,position_id,function_id,admission_date,termination_date").eq("tenant_id",tenantId).is("deleted_at",null).order("name");if(error)setError(error.message);else setRows((data??[]) as Employee[])}
 useEffect(()=>{void load()},[tenantId]);
 function start(){setForm(empty);setBirthUf("");setPixType("");setSection("Profissional");setEditing(true);setError(null);setOk(null)}
 function inferPixType(x:Form):PixType{const key=x.pix_key.trim();if(!key)return "";if(x.cpf&&digits(key)===digits(x.cpf))return "cpf";if(x.email&&key.toLowerCase()===x.email.trim().toLowerCase())return "email";if(x.phone&&digits(key)===digits(x.phone))return "phone";return "other"}
 async function edit(e:Employee){if(!supabase||!tenantId)return;setError(null);const [p,a,d,b,c]=await Promise.all([supabase.from("rh_employee_personal_details").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_addresses").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_documents").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_bank_accounts").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle(),supabase.from("rh_employee_compensation").select("*").eq("tenant_id",tenantId).eq("employee_id",e.id).maybeSingle()]);const bad=[p,a,d,b,c].find(x=>x.error);if(bad?.error){setError(bad.error.message);return}const x:any={...empty,...e,...(p.data||{}),...(a.data||{}),...(d.data||{}),...(b.data||{}),...(c.data||{}),id:e.id,salary:c.data?.salary==null?"":String(c.data.salary)};for(const k of Object.keys(empty) as (keyof Form)[])if(x[k]===null)x[k]="";if(x.cpf)x.cpf=maskCpf(x.cpf);if(x.phone)x.phone=maskPhone(x.phone);if(x.emergency_contact_phone)x.emergency_contact_phone=maskPhone(x.emergency_contact_phone);if(x.postal_code)x.postal_code=maskCep(x.postal_code);const m=String(x.birth_place||"").match(/^(.*) - ([A-Z]{2})$/);if(m){x.birth_place=m[1];setBirthUf(m[2])}else setBirthUf("");setForm(x);setPixType(inferPixType(x));setSection("Profissional");setEditing(true)}
 async function upsert(table:string,employeeId:string,payload:Record<string,unknown>){if(!supabase||!tenantId)return;const {data}=await supabase.from(table).select("id").eq("tenant_id",tenantId).eq("employee_id",employeeId).maybeSingle();const q=data?.id?supabase.from(table).update(payload).eq("id",data.id):supabase.from(table).insert({tenant_id:tenantId,employee_id:employeeId,...payload});const {error}=await q;if(error)throw error}
 function changePixType(type:PixType){setPixType(type);setForm(v=>({...v,pix_key:type==="cpf"?digits(v.cpf):type==="email"?v.email.trim():type==="phone"?v.phone:type===""?"":type==="random"?"":v.pix_key}))}
 useEffect(()=>{if(pixType==="cpf")setForm(v=>({...v,pix_key:digits(v.cpf)}));else if(pixType==="email")setForm(v=>({...v,pix_key:v.email.trim()}));else if(pixType==="phone")setForm(v=>({...v,pix_key:v.phone}))},[form.cpf,form.email,form.phone,pixType]);
 async function save(){if(!supabase||!tenantId||!form.name.trim())return;setSaving(true);setError(null);setOk(null);try{const {data:u,error:ue}=await supabase.auth.getUser();if(ue)throw ue;const main={tenant_id:tenantId,name:form.name.trim(),status:form.status,department_id:val(form.department_id),position_id:val(form.position_id),function_id:val(form.function_id),admission_date:val(form.admission_date),termination_date:val(form.termination_date),updated_by:u.user?.id??null};let employeeId=form.id;if(employeeId){const {error}=await supabase.from("rh_employees").update(main).eq("id",employeeId).eq("tenant_id",tenantId);if(error)throw error}else{const {data,error}=await supabase.from("rh_employees").insert({...main,created_by:u.user?.id??null}).select("id").single();if(error)throw error;employeeId=data.id}const natural=form.nationality==="Brasileira"&&form.birth_place&&birthUf?`${form.birth_place} - ${birthUf}`:form.birth_place;await upsert("rh_employee_personal_details",employeeId!,{cpf:val(form.cpf)?digits(form.cpf):null,rg:val(form.rg),birth_date:val(form.birth_date),sex:val(form.sex),marital_status:val(form.marital_status),nationality:val(form.nationality),birth_place:val(natural),mother_name:val(form.mother_name),father_name:val(form.father_name),phone:val(form.phone),email:val(form.email),emergency_contact_name:val(form.emergency_contact_name),emergency_contact_relationship:val(form.emergency_contact_relationship),emergency_contact_phone:val(form.emergency_contact_phone)});await upsert("rh_employee_addresses",employeeId!,{postal_code:val(form.postal_code),street:val(form.street),number:val(form.number),complement:val(form.complement),district:val(form.district),city:val(form.city),state:val(form.state)});await upsert("rh_employee_documents",employeeId!,{pis_pasep:val(form.pis_pasep),ctps:val(form.ctps),voter_registration:val(form.voter_registration),military_certificate:val(form.military_certificate),cnh:val(form.cnh),cnh_category:val(form.cnh_category),cnh_expires_at:val(form.cnh_expires_at)});await upsert("rh_employee_bank_accounts",employeeId!,{bank_name:val(form.bank_name),agency:val(form.agency),account_number:val(form.account_number),account_type:val(form.account_type),pix_key:val(form.pix_key)});await upsert("rh_employee_compensation",employeeId!,{salary:form.salary.trim()===""?null:Number(form.salary.replace(",","."))});setEditing(false);setForm(empty);setPixType("");setOk("Colaborador salvo com sucesso.");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o colaborador.")}finally{setSaving(false)}}
 const F=useMemo(()=>function StableField(props:{k:keyof Form;label:string;type?:string;mask?:(v:string)=>string}){return <Field {...props} form={formRef.current} setForm={setForm}/>},[]);
 return <div className="space-y-4">{error&&<div className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}{ok&&<div className="rounded-md border border-emerald-500/40 bg-emerald-500/10 p-3 text-sm">{ok}</div>}{!editing&&<><div className="flex justify-end"><button onClick={start} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><Plus className="h-4 w-4"/>Novo colaborador</button></div>{rows.length===0?<div className="rounded-lg border border-dashed p-8 text-center"><UserRound className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><div className="font-semibold">Nenhum colaborador cadastrado</div></div>:<div className="grid gap-3 md:grid-cols-2">{rows.map(r=><div key={r.id} className="rounded-lg border p-4 flex justify-between gap-3"><div><div className="font-semibold">{r.name}</div><div className="text-sm text-muted-foreground">{r.status}</div></div><button onClick={()=>void edit(r)} className="rounded-md p-2 hover:bg-muted"><Pencil className="h-4 w-4"/></button></div>)}</div>}</>}{editing&&<div className="space-y-5"><div className="flex flex-wrap gap-2">{sections.map(s=><button key={s} onClick={()=>setSection(s)} className={`rounded-md border px-3 py-2 text-sm ${section===s?"bg-primary text-primary-foreground":"bg-background"}`}>{s}</button>)}</div><div className="grid gap-4 md:grid-cols-2">
 {section==="Profissional"&&<><F k="name" label="Nome completo *"/><Select label="Status" value={form.status} onChange={x=>setForm(v=>({...v,status:x}))}><option value="ativo">Ativo</option><option value="inativo">Inativo</option><option value="desligado">Desligado</option></Select><Select label="Departamento" value={form.department_id} onChange={x=>setForm(v=>({...v,department_id:x,position_id:"",function_id:""}))}><option value="">Selecione</option>{departments.filter(x=>x.status==="ativo").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Cargo" value={form.position_id} onChange={x=>setForm(v=>({...v,position_id:x,function_id:""}))}><option value="">Selecione</option>{positionsFiltered.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Função" value={form.function_id} onChange={x=>setForm(v=>({...v,function_id:x}))}><option value="">Selecione</option>{functionsFiltered.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select><F k="admission_date" label="Admissão" type="date"/><F k="termination_date" label="Desligamento" type="date"/></>}
 {section==="Pessoal"&&<><F k="cpf" label="CPF" mask={maskCpf}/><F k="rg" label="RG"/><F k="birth_date" label="Nascimento" type="date"/><Select label="Sexo" value={form.sex} onChange={x=>setForm(v=>({...v,sex:x}))}><option value="">Selecione</option>{sexes.map(x=><option key={x}>{x}</option>)}</Select><Select label="Estado civil" value={form.marital_status} onChange={x=>setForm(v=>({...v,marital_status:x}))}><option value="">Selecione</option>{marital.map(x=><option key={x}>{x}</option>)}</Select><Select label="Nacionalidade" value={form.nationality} onChange={x=>{setForm(v=>({...v,nationality:x,birth_place:""}));setBirthUf("")}}><option>Brasileira</option><option>Estrangeira</option></Select>{form.nationality==="Brasileira"?<><Select label="UF de nascimento" value={birthUf} onChange={x=>{setBirthUf(x);setForm(v=>({...v,birth_place:""}))}}><option value="">Selecione</option>{ufs.map(x=><option key={x.sigla} value={x.sigla}>{x.nome} ({x.sigla})</option>)}</Select><Select label="Naturalidade / Município" value={form.birth_place} disabled={!birthUf} onChange={x=>setForm(v=>({...v,birth_place:x}))}><option value="">Selecione</option>{birthCities.map(x=><option key={x.id} value={x.nome}>{x.nome}</option>)}</Select></>:<F k="birth_place" label="Naturalidade"/>}<F k="phone" label="Telefone (+55 + DDD + número)" mask={maskPhone}/><F k="email" label="E-mail" type="email"/><F k="mother_name" label="Nome da mãe"/><F k="father_name" label="Nome do pai"/><F k="emergency_contact_name" label="Contato de emergência"/><F k="emergency_contact_relationship" label="Parentesco"/><F k="emergency_contact_phone" label="Telefone de emergência" mask={maskPhone}/></>}
 {section==="Endereço"&&<><F k="postal_code" label="CEP" mask={maskCep}/><F k="street" label="Logradouro"/><F k="number" label="Número"/><F k="complement" label="Complemento"/><F k="district" label="Bairro"/><Select label="UF" value={form.state} onChange={x=>setForm(v=>({...v,state:x,city:""}))}><option value="">Selecione</option>{ufs.map(x=><option key={x.sigla} value={x.sigla}>{x.nome} ({x.sigla})</option>)}</Select><Select label="Cidade" value={form.city} disabled={!form.state} onChange={x=>setForm(v=>({...v,city:x}))}><option value="">Selecione</option>{addressCities.map(x=><option key={x.id} value={x.nome}>{x.nome}</option>)}</Select></>}
 {section==="Documentos"&&<><F k="pis_pasep" label="PIS/PASEP"/><F k="ctps" label="CTPS"/><F k="voter_registration" label="Título de eleitor"/><F k="military_certificate" label="Reservista"/><F k="cnh" label="CNH"/><Select label="Categoria CNH" value={form.cnh_category} onChange={x=>setForm(v=>({...v,cnh_category:x}))}><option value="">Selecione</option>{cnhCategories.map(x=><option key={x}>{x}</option>)}</Select><F k="cnh_expires_at" label="Validade CNH" type="date"/></>}
 {section==="Banco e remuneração"&&<><Select label="Banco (código - instituição)" value={form.bank_name} onChange={x=>setForm(v=>({...v,bank_name:x}))}><option value="">Selecione</option>{banks.map(b=><option key={`${b.ispb}-${b.code??""}`} value={b.fullName||b.name}>{b.code!=null?`${String(b.code).padStart(3,"0")} - `:"Sem código - "}{b.name}</option>)}</Select><F k="agency" label="Agência"/><F k="account_number" label="Conta"/><Select label="Tipo de conta" value={form.account_type} onChange={x=>setForm(v=>({...v,account_type:x}))}><option value="">Selecione</option>{accountTypes.map(x=><option key={x}>{x}</option>)}</Select><Select label="Tipo de chave PIX" value={pixType} onChange={x=>changePixType(x as PixType)}><option value="">Selecione</option><option value="cpf">CPF do colaborador</option><option value="email">E-mail do colaborador</option><option value="phone">Telefone do colaborador</option><option value="random">Chave aleatória</option><option value="other">Outra chave</option></Select>{pixType==="cpf"?<label className="space-y-1.5"><span className="text-sm font-medium">Chave PIX</span><input className={input} value={maskCpf(form.pix_key)} readOnly/></label>:pixType==="email"||pixType==="phone"?<label className="space-y-1.5"><span className="text-sm font-medium">Chave PIX</span><input className={input} value={form.pix_key} readOnly/></label>:<F k="pix_key" label={pixType==="random"?"Chave PIX aleatória":"Chave PIX"}/>}<F k="salary" label="Salário" type="number"/></>}
 </div><div className="flex justify-end gap-2"><button className="h-10 rounded-md border px-4 text-sm" onClick={()=>setEditing(false)}>Cancelar</button><button disabled={saving||!form.name.trim()} className="h-10 rounded-md bg-primary px-5 text-sm font-medium text-primary-foreground disabled:opacity-50" onClick={()=>void save()}>{saving?"Salvando...":"Salvar colaborador"}</button></div></div>}</div>
}
