/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppEmpresaRouteImport } from './routes/app/empresa'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppObrasRouteImport } from './routes/app/obras'
import { Route as AppRhRouteImport } from './routes/app/rh'
import { Route as AppSuprimentosRouteImport } from './routes/app/suprimentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppSuprimentosRoute = AppSuprimentosRouteImport.update({
  id: '/suprimentos',
  path: '/suprimentos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/obras': typeof AppObrasRoute
  '/app/rh': typeof AppRhRoute
  '/app/suprimentos': typeof AppSuprimentosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/obras': typeof AppObrasRoute
  '/app/rh': typeof AppRhRoute
  '/app/suprimentos': typeof AppSuprimentosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/obras': typeof AppObrasRoute
  '/app/rh': typeof AppRhRoute
  '/app/suprimentos': typeof AppSuprimentosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/dashboard'
    | '/app/empresa'
    | '/app/financeiro'
    | '/app/obras'
    | '/app/rh'
    | '/app/suprimentos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/app/dashboard'
    | '/app/empresa'
    | '/app/financeiro'
    | '/app/obras'
    | '/app/rh'
    | '/app/suprimentos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/app/dashboard'
    | '/app/empresa'
    | '/app/financeiro'
    | '/app/obras'
    | '/app/rh'
    | '/app/suprimentos'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresa': {
      id: '/app/empresa'
      path: '/empresa'
      fullPath: '/app/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/obras': {
      id: '/app/obras'
      path: '/obras'
      fullPath: '/app/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh': {
      id: '/app/rh'
      path: '/rh'
      fullPath: '/app/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suprimentos': {
      id: '/app/suprimentos'
      path: '/suprimentos'
      fullPath: '/app/suprimentos'
      preLoaderRoute: typeof AppSuprimentosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppObrasRoute: typeof AppObrasRoute
  AppRhRoute: typeof AppRhRoute
  AppSuprimentosRoute: typeof AppSuprimentosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppObrasRoute: AppObrasRoute,
  AppRhRoute: AppRhRoute,
  AppSuprimentosRoute: AppSuprimentosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
